// src/pages/MenuEditor.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import MenuPreview from '../components/Editor/MenuPreview.svelte';
  import SliceList from '../components/Editor/SliceList.svelte';
  import SliceEditor from '../components/Editor/SliceEditor.svelte';
  import AppearancePanel from '../components/Editor/AppearancePanel.svelte';
  import { t } from '../i18n';
  import { navigate } from '../stores/router';
  import { settingsStore } from '../stores/settingsStore';
  import { historyStore } from '../stores/historyStore';
  import type { Appearance, Settings, Slice } from '../types/settings';

  export let id: string | undefined = undefined;

  let settings: Settings | null = null;
  let selectedSliceId: string | null = null;
  let activeTab: 'slices' | 'appearance' = 'slices';
  let canUndoValue = false;
  let canRedoValue = false;
  let saveTimer: ReturnType<typeof setTimeout> | undefined;

  $: settings = $settingsStore.settings;
  $: canUndoValue = $historyStore.undoStack.length >= 2;
  $: canRedoValue = $historyStore.redoStack.length > 0;
  $: menuId = id;
  $: menu = settings?.menus.find((candidate) => candidate.id === menuId);
  $: selectedSlice = menu?.slices.find((slice) => slice.id === selectedSliceId);
  $: selectedIndex = menu?.slices.findIndex((slice) => slice.id === selectedSliceId) ?? -1;
  $: appearance = settings?.global.appearance;
  $: menuIds = settings?.menus.filter((candidate) => candidate.id !== menuId).map((candidate) => candidate.id) ?? [];

  onMount(() => {
    if (!$settingsStore.settings && !$settingsStore.loading) {
      void settingsStore.loadSettings();
    }

    window.addEventListener('keydown', handleKeyDown);
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
    };
  });

  onDestroy(() => {
    if (saveTimer) clearTimeout(saveTimer);
  });

  function pushSnapshot() {
    if (!settings) return;
    historyStore.pushSnapshot(settings);
  }

  function debouncedSave() {
    if (saveTimer) clearTimeout(saveTimer);
    saveTimer = setTimeout(() => {
      void settingsStore.saveSettings();
    }, 500);
  }

  function restoreSnapshot(snapshot: Settings | null | undefined) {
    if (!snapshot) return;
    settingsStore.setSettings(snapshot);
    void settingsStore.saveSettings();
  }

  function handleUndo() {
    restoreSnapshot(historyStore.undo());
  }

  function handleRedo() {
    restoreSnapshot(historyStore.redo());
  }

  function handleKeyDown(event: KeyboardEvent) {
    if ((event.ctrlKey || event.metaKey) && event.key === 'z' && !event.shiftKey) {
      event.preventDefault();
      handleUndo();
    }

    if ((event.ctrlKey || event.metaKey) && event.key === 'z' && event.shiftKey) {
      event.preventDefault();
      handleRedo();
    }
  }

  function handleMenuNameChange(name: string) {
    if (!settings || !menuId) return;
    pushSnapshot();
    settingsStore.updateMenu(menuId, { name });
    debouncedSave();
  }

  function handleSliceReorder(slices: Slice[]) {
    if (!settings || !menuId) return;
    pushSnapshot();
    settingsStore.updateMenu(menuId, { slices });
    debouncedSave();
  }

  function handleAddSlice() {
    if (!settings || !menu || !menuId) return;
    pushSnapshot();
    const newSlice: Slice = {
      id: `s_${Date.now()}`,
      label: `Action ${menu.slices.length + 1}`,
      icon: '⚡',
      actions: [{ type: 'noop', params: {} }],
    };
    settingsStore.updateMenu(menuId, { slices: [...menu.slices, newSlice] });
    selectedSliceId = newSlice.id;
    debouncedSave();
  }

  function handleDeleteSlice(sliceId: string) {
    if (!settings || !menu || !menuId) return;
    pushSnapshot();
    settingsStore.updateMenu(menuId, { slices: menu.slices.filter((slice) => slice.id !== sliceId) });
    if (selectedSliceId === sliceId) selectedSliceId = null;
    debouncedSave();
  }

  function handleSliceChange(updates: Partial<Slice>) {
    if (!settings || !menu || !menuId || !selectedSliceId) return;
    pushSnapshot();
    settingsStore.updateMenu(menuId, {
      slices: menu.slices.map((slice) => (slice.id === selectedSliceId ? { ...slice, ...updates } : slice)),
    });
    debouncedSave();
  }

  function handleAppearanceChange(updates: Partial<Appearance>) {
    if (!settings || !appearance) return;
    pushSnapshot();
    settingsStore.updateGlobalSettings({ appearance: { ...appearance, ...updates } });
    debouncedSave();
  }

  function handleDeleteMenu() {
    if (!menuId || !confirm($t('editor.deleteConfirm'))) return;
    settingsStore.deleteMenu(menuId);
    void settingsStore.saveSettings();
    navigate('/');
  }
</script>

{#if !settings || !menu || !appearance}
  <div class="text-theme-text-secondary">Menu not found</div>
{:else}
  <div class="flex flex-col h-full">
    <div class="flex items-center gap-4 mb-6">
      <button
        type="button"
        on:click={() => navigate('/')}
        class="text-theme-text-secondary hover:text-theme-text-primary text-sm"
      >
        {$t('editor.back')}
      </button>
      <input
        type="text"
        value={menu.name}
        on:input={(event) => handleMenuNameChange(event.currentTarget.value)}
        class="text-2xl font-bold bg-transparent border-none outline-none focus:ring-1 focus:ring-blue-500 rounded px-1"
      />
      <div class="flex items-center gap-1 ml-2">
        <button
          type="button"
          on:click={handleUndo}
          disabled={!canUndoValue}
          class="px-2 py-1 text-sm rounded bg-theme-bg-tertiary disabled:opacity-30 hover:bg-theme-bg-tertiary/80 disabled:cursor-not-allowed"
          title="Undo (Ctrl+Z)"
        >
          ↶
        </button>
        <button
          type="button"
          on:click={handleRedo}
          disabled={!canRedoValue}
          class="px-2 py-1 text-sm rounded bg-theme-bg-tertiary disabled:opacity-30 hover:bg-theme-bg-tertiary/80 disabled:cursor-not-allowed"
          title="Redo (Ctrl+Shift+Z)"
        >
          ↷
        </button>
      </div>
      <button
        type="button"
        on:click={handleDeleteMenu}
        class="ml-auto text-sm text-theme-text-muted hover:text-red-400 transition-colors"
      >
        {$t('editor.deleteMenu')}
      </button>
    </div>

    <div class="flex gap-6 flex-1 min-h-0">
      <div class="w-1/2 flex flex-col gap-4">
        <MenuPreview
          slices={menu.slices}
          selectedIndex={selectedIndex >= 0 ? selectedIndex : null}
          {appearance}
        />
      </div>

      <div class="w-1/2 flex flex-col gap-4 overflow-auto">
        <div class="flex gap-1 bg-theme-bg-secondary rounded-lg p-1">
          <button
            type="button"
            on:click={() => {
              activeTab = 'slices';
            }}
            class="flex-1 text-sm py-1.5 rounded-md transition-colors {activeTab === 'slices'
              ? 'bg-theme-bg-tertiary text-theme-text-primary'
              : 'text-theme-text-secondary hover:text-theme-text-primary'}"
          >
            {$t('editor.slices')}
          </button>
          <button
            type="button"
            on:click={() => {
              activeTab = 'appearance';
            }}
            class="flex-1 text-sm py-1.5 rounded-md transition-colors {activeTab === 'appearance'
              ? 'bg-theme-bg-tertiary text-theme-text-primary'
              : 'text-theme-text-secondary hover:text-theme-text-primary'}"
          >
            {$t('editor.appearance')}
          </button>
        </div>

        {#if activeTab === 'slices'}
          <div class="space-y-4">
            <SliceList
              slices={menu.slices}
              selectedId={selectedSliceId}
              onSelect={(sliceId) => {
                selectedSliceId = sliceId;
              }}
              onReorder={handleSliceReorder}
              onAdd={handleAddSlice}
              onDelete={handleDeleteSlice}
            />
            {#if selectedSlice}
              <div class="border-t border-theme-border pt-4">
                <SliceEditor slice={selectedSlice} onChange={handleSliceChange} {menuIds} />
              </div>
            {/if}
          </div>
        {/if}

        {#if activeTab === 'appearance'}
          <AppearancePanel {appearance} onChange={handleAppearanceChange} />
        {/if}
      </div>
    </div>
  </div>
{/if}

// src/pages/MenuEditor.tsx
import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useSettingsStore } from '../stores/settingsStore';
import { useHistoryStore } from '../stores/historyStore';
import { MenuPreview } from '../components/Editor/MenuPreview';
import { SliceList } from '../components/Editor/SliceList';
import { SliceEditor } from '../components/Editor/SliceEditor';
import { AppearancePanel } from '../components/Editor/AppearancePanel';
import { useTranslation } from 'react-i18next';
import type { Slice } from '../types/settings';

export const MenuEditor: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { settings, updateMenu, saveSettings, deleteMenu, loadSettings, setSettings } = useSettingsStore();
  const { pushSnapshot, undo, redo, canUndo, canRedo } = useHistoryStore();
  const { t } = useTranslation();
  const [selectedSliceId, setSelectedSliceId] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'slices' | 'appearance'>('slices');
  const saveTimerRef = useRef<ReturnType<typeof setTimeout>>();

  useEffect(() => {
    if (!settings) loadSettings();
  }, [settings, loadSettings]);

  const menu = settings?.menus.find((m) => m.id === id);

  // Auto-save with debounce
  const debouncedSave = useCallback(() => {
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    saveTimerRef.current = setTimeout(() => {
      saveSettings();
    }, 500);
  }, [saveSettings]);

  useEffect(() => {
    return () => {
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    };
  }, []);

  // Keyboard shortcuts for undo/redo
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) {
        e.preventDefault();
        const restored = undo();
        if (restored) {
          setSettings(restored);
          saveSettings();
        }
      }
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && e.shiftKey) {
        e.preventDefault();
        const restored = redo();
        if (restored) {
          setSettings(restored);
          saveSettings();
        }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [undo, redo, setSettings, saveSettings]);

  if (!settings || !menu) return <div className="text-theme-text-secondary">Menu not found</div>;

  const selectedSlice = menu.slices.find((s) => s.id === selectedSliceId);
  const selectedIndex = menu.slices.findIndex((s) => s.id === selectedSliceId);
  const appearance = settings.global.appearance;
  const menuIds = settings.menus.filter((m) => m.id !== id).map((m) => m.id);

  const handleMenuNameChange = (name: string) => {
    pushSnapshot(settings);
    updateMenu(id!, { name });
    debouncedSave();
  };

  const handleSliceReorder = (slices: Slice[]) => {
    pushSnapshot(settings);
    updateMenu(id!, { slices });
    debouncedSave();
  };

  const handleAddSlice = () => {
    pushSnapshot(settings);
    const newSlice: Slice = {
      id: `s_${Date.now()}`,
      label: `Action ${menu.slices.length + 1}`,
      icon: '⚡',
      actions: [{ type: 'noop', params: {} }],
    };
    updateMenu(id!, { slices: [...menu.slices, newSlice] });
    setSelectedSliceId(newSlice.id);
    debouncedSave();
  };

  const handleDeleteSlice = (sliceId: string) => {
    pushSnapshot(settings);
    const newSlices = menu.slices.filter((s) => s.id !== sliceId);
    updateMenu(id!, { slices: newSlices });
    if (selectedSliceId === sliceId) setSelectedSliceId(null);
    debouncedSave();
  };

  const handleSliceChange = (updates: Partial<Slice>) => {
    if (!selectedSliceId) return;
    pushSnapshot(settings);
    const newSlices = menu.slices.map((s) =>
      s.id === selectedSliceId ? { ...s, ...updates } : s
    );
    updateMenu(id!, { slices: newSlices });
    debouncedSave();
  };

  const handleAppearanceChange = (updates: Partial<typeof appearance>) => {
    const { updateGlobalSettings } = useSettingsStore.getState();
    pushSnapshot(settings);
    updateGlobalSettings({ appearance: { ...appearance, ...updates } });
    debouncedSave();
  };

  const handleDeleteMenu = () => {
    if (confirm(t('editor.deleteConfirm'))) {
      deleteMenu(id!);
      saveSettings();
      navigate('/');
    }
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <button
          onClick={() => navigate('/')}
          className="text-theme-text-secondary hover:text-theme-text-primary text-sm"
        >
          {t('editor.back')}
        </button>
        <input
          type="text"
          value={menu.name}
          onChange={(e) => handleMenuNameChange(e.target.value)}
          className="text-2xl font-bold bg-transparent border-none outline-none focus:ring-1 focus:ring-blue-500 rounded px-1"
        />
        <div className="flex items-center gap-1 ml-2">
          <button
            onClick={() => { const s = undo(); if (s) { setSettings(s); saveSettings(); } }}
            disabled={!canUndo()}
            className="px-2 py-1 text-sm rounded bg-theme-bg-tertiary disabled:opacity-30 hover:bg-theme-bg-tertiary/80 disabled:cursor-not-allowed"
            title="Undo (Ctrl+Z)"
          >
            ↶
          </button>
          <button
            onClick={() => { const s = redo(); if (s) { setSettings(s); saveSettings(); } }}
            disabled={!canRedo()}
            className="px-2 py-1 text-sm rounded bg-theme-bg-tertiary disabled:opacity-30 hover:bg-theme-bg-tertiary/80 disabled:cursor-not-allowed"
            title="Redo (Ctrl+Shift+Z)"
          >
            ↷
          </button>
        </div>
        <button
          onClick={handleDeleteMenu}
          className="ml-auto text-sm text-theme-text-muted hover:text-red-400 transition-colors"
        >
          {t('editor.deleteMenu')}
        </button>
      </div>

      {/* Main editor area */}
      <div className="flex gap-6 flex-1 min-h-0">
        {/* Left: Preview */}
        <div className="w-1/2 flex flex-col gap-4">
          <MenuPreview
            slices={menu.slices}
            selectedIndex={selectedIndex >= 0 ? selectedIndex : null}
            appearance={appearance}
          />
        </div>

        {/* Right: Editor panels */}
        <div className="w-1/2 flex flex-col gap-4 overflow-auto">
          {/* Tab bar */}
          <div className="flex gap-1 bg-theme-bg-secondary rounded-lg p-1">
            <button
              onClick={() => setActiveTab('slices')}
              className={`flex-1 text-sm py-1.5 rounded-md transition-colors ${
                activeTab === 'slices' ? 'bg-theme-bg-tertiary text-theme-text-primary' : 'text-theme-text-secondary hover:text-theme-text-primary'
              }`}
            >
              {t('editor.slices')}
            </button>
            <button
              onClick={() => setActiveTab('appearance')}
              className={`flex-1 text-sm py-1.5 rounded-md transition-colors ${
                activeTab === 'appearance' ? 'bg-theme-bg-tertiary text-theme-text-primary' : 'text-theme-text-secondary hover:text-theme-text-primary'
              }`}
            >
              {t('editor.appearance')}
            </button>
          </div>

          {activeTab === 'slices' && (
            <div className="space-y-4">
              <SliceList
                slices={menu.slices}
                selectedId={selectedSliceId}
                onSelect={setSelectedSliceId}
                onReorder={handleSliceReorder}
                onAdd={handleAddSlice}
                onDelete={handleDeleteSlice}
              />
              {selectedSlice && (
                <div className="border-t border-theme-border pt-4">
                  <SliceEditor
                    slice={selectedSlice}
                    onChange={handleSliceChange}
                    menuIds={menuIds}
                  />
                </div>
              )}
            </div>
          )}

          {activeTab === 'appearance' && (
            <AppearancePanel
              appearance={appearance}
              onChange={handleAppearanceChange}
            />
          )}
        </div>
      </div>
    </div>
  );
};
