// src/App.tsx
import React, { useEffect } from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { Layout } from './components/Layout/Layout';
import { Dashboard } from './pages/Dashboard';
import { MenuEditor } from './pages/MenuEditor';
import { Profiles } from './pages/Profiles';
import { GlobalSettings } from './pages/GlobalSettings';
import { useSettingsStore } from './stores/settingsStore';
import type { AppTheme } from './types/settings';

function applyThemeClass(theme: AppTheme) {
  const root = document.documentElement;
  if (theme === 'dark') {
    root.classList.add('dark');
  } else if (theme === 'light') {
    root.classList.remove('dark');
  } else {
    // system
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    if (prefersDark) {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  }
}

const App: React.FC = () => {
  const theme = useSettingsStore((s) => s.settings?.global.theme ?? 'dark');

  useEffect(() => {
    applyThemeClass(theme);

    if (theme === 'system') {
      const mq = window.matchMedia('(prefers-color-scheme: dark)');
      const handler = () => applyThemeClass('system');
      mq.addEventListener('change', handler);
      return () => mq.removeEventListener('change', handler);
    }
  }, [theme]);

  return (
    <BrowserRouter>
      <Routes>
        <Route element={<Layout />}>
          <Route path="/" element={<Dashboard />} />
          <Route path="/menu/:id" element={<MenuEditor />} />
          <Route path="/profiles" element={<Profiles />} />
          <Route path="/settings" element={<GlobalSettings />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
};

export default App;

// src/App.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import type { Component } from "svelte";
  import Layout from "./components/Layout/Layout.svelte";
  import Dashboard from "./pages/Dashboard.svelte";
  import GlobalSettings from "./pages/GlobalSettings.svelte";
  import Profiles from "./pages/Profiles.svelte";
  import { t } from "./i18n";
  import { route } from "./stores/router";
  import { settingsStore } from "./stores/settingsStore";
  import type { AppTheme } from "./types/settings";

  let MenuEditor: Component<Record<string, string>> | null = null;
  let mediaQuery: MediaQueryList | null = null;

  function applyThemeClass(theme: AppTheme) {
    const root = document.documentElement;
    if (theme === "dark") {
      root.classList.add("dark");
    } else if (theme === "light") {
      root.classList.remove("dark");
    } else {
      const prefersDark = window.matchMedia(
        "(prefers-color-scheme: dark)",
      ).matches;
      root.classList.toggle("dark", prefersDark);
    }
  }

  function handleSystemThemeChange() {
    applyThemeClass("system");
  }

  async function loadMenuEditor() {
    if (MenuEditor) return;
    const module = await import("./pages/MenuEditor.svelte");
    MenuEditor = module.default;
  }

  onMount(() => {
    void settingsStore.loadSettings();
  });

  $: theme = $settingsStore.settings?.global.theme ?? "dark";

  $: {
    applyThemeClass(theme);
    mediaQuery?.removeEventListener("change", handleSystemThemeChange);
    mediaQuery = null;

    if (theme === "system") {
      mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
      mediaQuery.addEventListener("change", handleSystemThemeChange);
    }
  }

  $: if ($route.name === "menu") {
    void loadMenuEditor();
  }

  onDestroy(() => {
    mediaQuery?.removeEventListener("change", handleSystemThemeChange);
  });
</script>

<Layout>
  {#if $route.name === "dashboard"}
    <Dashboard />
  {:else if $route.name === "profiles"}
    <Profiles />
  {:else if $route.name === "settings"}
    <GlobalSettings />
  {:else if $route.name === "menu"}
    {#if MenuEditor}
      <svelte:component this={MenuEditor} id={$route.params.id} />
    {:else}
      <div class="text-theme-text-secondary">{$t("common.loading")}</div>
    {/if}
  {:else}
    <div class="text-theme-text-secondary">{$t("common.pageNotFound")}</div>
  {/if}
</Layout>
